name: Test LXD VM with OpenTofu

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lxd-opentofu-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check KVM support
        run: |
          echo "Checking KVM kernel module availability..."
          lsmod | grep kvm || echo "KVM modules not loaded"
          ls -la /dev/kvm || echo "/dev/kvm not available"

      - name: Install and configure LXD
        run: |
          sudo snap install lxd
          # Wait for LXD daemon to start
          echo "Waiting for LXD daemon to start..."
          sleep 15
          # Initialize LXD with default settings
          sudo lxd init --auto
          # Add runner to lxd group
          sudo usermod -a -G lxd runner
          # Fix socket permissions for CI environment
          sudo chmod 666 /var/snap/lxd/common/lxd/unix.socket
          # Test basic LXD functionality
          sudo lxc list

      - name: Install OpenTofu
        run: |
          # Check if tofu is already installed
          if command -v tofu &> /dev/null; then
              echo "OpenTofu is already installed, skipping installation"
              exit 0
          fi

          # Download and install OpenTofu using official installer
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          chmod +x install-opentofu.sh
          sudo ./install-opentofu.sh --install-method deb
          rm install-opentofu.sh
          tofu version

      - name: Initialize and apply OpenTofu
        working-directory: config/tofu/lxd
        run: |
          tofu init
          tofu validate
          tofu plan
          sudo -E tofu apply -auto-approve

      - name: Test LXD VM functionality
        run: |
          # Wait for VM to start
          sleep 15

          # Test basic functionality
          sudo lxc list
          sudo lxc info test-vm

          # Wait for container to be ready
          echo "Waiting for VM to be fully initialized..."
          sleep 15

          # Wait up to 5 minutes for cloud-init to complete
          timeout=300
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if sudo lxc exec test-vm -- test -f /tmp/provision_complete 2>/dev/null; then
              echo "VM provisioning completed successfully!"
              break
            fi
            echo "Waiting for VM provisioning to complete... ($elapsed/$timeout seconds)"
            sleep 10
            elapsed=$((elapsed + 10))
          done

          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for VM provisioning to complete"
            exit 1
          fi

          # Test command execution
          sudo lxc exec test-vm -- bash -c "echo Hello from LXD VM via OpenTofu"
          sudo lxc exec test-vm -- cat /etc/os-release
          sudo lxc exec test-vm -- cloud-init status
          sudo lxc exec test-vm -- systemctl status ssh --no-pager

      - name: Get OpenTofu outputs
        working-directory: config/tofu/lxd
        run: sudo -E tofu output

      - name: Cleanup
        if: always()
        working-directory: config/tofu/lxd
        run: |
          echo "Cleaning up..."
          sudo -E tofu destroy -auto-approve || true
          sudo lxc delete test-vm --force || true
          sudo lxc profile delete test-profile || true
          sudo lxc list
