name: Test LXD Provision

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lxd-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LXD
        run: |
          sudo snap install lxd
          sudo lxd init --auto
          sudo usermod -aG lxd $USER

      - name: Launch LXD container
        run: |
          sudo -u $USER lxc launch images:ubuntu/24.04 test-container
          sleep 10

      - name: Run command inside container
        run: |
          sudo -u $USER lxc exec test-container -- bash -c "echo Hello from LXD container"

      - name: Stop and delete container
        run: |
          sudo -u $USER lxc stop test-container
          sudo -u $USER lxc delete test-container
