name: Test LXD Provision

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lxd-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LXD
        run: |
          sudo snap install lxd
          sudo lxd init --auto
          sudo usermod -aG lxd $USER
          # Wait for LXD to be ready
          sleep 5

      - name: Launch LXD VM
        run: |
          sudo -u $USER lxc launch ubuntu:24.04 test-vm --vm
          sleep 15

      - name: Run command inside VM
        run: |
          sudo -u $USER lxc exec test-vm -- bash -c "echo Hello from LXD VM"

      - name: Stop and delete VM
        run: |
          sudo -u $USER lxc stop test-vm
          sudo -u $USER lxc delete test-vm
